name: Validate Header Bidding Code

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Use the latest stable version if necessary

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: npm install

      # Step 4: Run linting (optional but recommended for code quality)
      - name: Run Linter
        run: npm run lint  # Ensure you have a lint script in your package.json

      # Step 5: Run Prebid.js validation (basic check for syntax and dependencies)
      - name: Validate Prebid.js setup
        run: npm run validate  # Add this script in package.json if needed
